In [1]:
import pandas as pd
import ssl
import pandas_datareader as pdr

In [2]:
url = 'https://quality.data.gov.tw/dq_download_json.php?nid=11549&md5_url=da96048521360db9f23a2b47c9c31155'

### 台股

In [3]:
df = pd.read_json(url)
df

,證券代號,證券名稱,成交股數,成交金額,開盤價,最高價,最低價,收盤價,漲跌價差,成交筆數
0,0050,元大台灣50,31244250,3953298339,127.00,127.00,126.05,126.55,-2.70,50065
1,0051,元大中型100,94541,5298080,56.50,56.60,55.80,56.30,-1.10,473
2,0052,富邦科技,691549,71702988,103.65,104.00,103.15,103.55,-2.65,1035
3,0053,元大電子,6579,389089,59.05,59.30,59.00,59.30,-1.55,82
4,0054,元大台商50,74994,2127337,28.29,28.54,28.25,28.46,-0.40,916
...,...,...,...,...,...,...,...,...,...,...
1157,9944,新麗,145338,3003477,20.75,20.75,20.40,20.75,0.00,320
1158,9945,潤泰新,55467471,4315438183,79.20,79.50,75.50,78.90,4.40,32408
1159,9946,三發地產,124771,1580728,12.75,12.75,12.60,12.70,-0.05,139
1160,9955,佳龍,1701637,43126461,24.60,26.00,24.60,25.60,0.10,1033
1161,9958,世紀鋼,12458269,1635999119,130.00,134.00,128.00,134.00,0.50,7704

In [4]:
df.columns

Index(['證券代號', '證券名稱', '成交股數', '成交金額', '開盤價', '最高價', '最低價', '收盤價', '漲跌價差',
       '成交筆數'],
      dtype='object')

In [5]:
# def get_yahoo_stock(stock, start = 2022, end = 2023):
df = pdr.get_data_yahoo('TSLA', 2022, 2023)
df

,High,Low,Open,Close,Volume,Adj Close
Date,,,,,,
2021-12-31,1082.000000,1054.589966,1073.439941,1056.780029,13577900,1056.780029
2022-01-03,1201.069946,1136.040039,1147.750000,1199.780029,34643800,1199.780029
2022-01-04,1208.000000,1123.050049,1189.550049,1149.589966,33416100,1149.589966
2022-01-05,1170.339966,1081.010010,1146.650024,1088.119995,26706600,1088.119995
2022-01-06,1088.000000,1020.500000,1077.000000,1064.699951,30112200,1064.699951
...,...,...,...,...,...,...
2022-07-08,764.940002,723.479980,727.000000,752.289978,33343700,752.289978
2022-07-11,759.190002,700.880005,756.309998,703.030029,33080400,703.030029
2022-07-12,719.320007,685.109985,710.539978,699.210022,29310300,699.210022
2022-07-13,726.179993,675.099976,676.500000,711.119995,32651500,711.119995
2022-07-14,715.960022,688.000000,704.690002,714.940002,26069500,714.940002

In [6]:
def get_US_stock():
    df = pdr.get_data_yahoo('TSLA', 2022, 2023)
    times = df.index
    datas = []  # time
    for t in times:
        datas.append(t)
    df_highest = df['High'].to_list()
    df_lowest = df['Low'].to_list()
    df_open = df['Open'].to_list()
    df_Close = df['Close'].to_list()
    df_vol = df['Volume'].to_list()
    df_adj = df['Adj Close'].to_list()
    values = []
    for i in range(len(df_highest)):
        values.append([datas[i], round(df_highest[i], 2), round(df_lowest[i], 2),
                    round(df_open[i], 2), round(df_Close[i], 2), round(df_vol[i], 2), round(df_adj[i], 2)])
    values

In [7]:
df['Low'].to_list()

[1054.5899658203125,
 1136.0400390625,
 1123.050048828125,
 1081.010009765625,
 1020.5,
 1010.0,
 980.0,
 1038.8199462890625,
 1072.5899658203125,
 1026.5400390625,
 1013.3800048828125,
 1016.0599975585938,
 995.0,
 994.0,
 940.5,
 851.469970703125,
 903.2100219726562,
 906.0,
 829.0,
 792.010009765625,
 862.0499877929688,
 905.0,
 889.4099731445312,
 880.52001953125,
 881.1699829101562,
 902.7100219726562,
 894.7999877929688,
 920.0,
 896.7000122070312,
 850.7000122070312,
 853.1500244140625,
 893.3800048828125,
 901.2100219726562,
 874.0999755859375,
 837.6099853515625,
 801.0999755859375,
 760.5599975585938,
 700.0,
 782.4000244140625,
 814.7100219726562,
 853.780029296875,
 844.27001953125,
 832.5999755859375,
 825.1599731445312,
 804.5700073242188,
 782.1699829101562,
 832.010009765625,
 810.3599853515625,
 793.77001953125,
 756.0399780273438,
 756.5700073242188,
 802.260009765625,
 825.719970703125,
 867.3900146484375,
 907.0900268554688,
 921.75,
 976.4000244140625,
 988.7999877929688,
 997.3200073242188,
 1053.5999755859375,
 1073.1099853515625,
 1084.0,
 1076.6400146484375,
 1066.6400146484375,
 1072.530029296875,
 1087.300048828125,
 1027.699951171875,
 1021.5399780273438,
 1022.4400024414062,
 974.6400146484375,
 976.5999755859375,
 973.0999755859375,
 982.1900024414062,
 973.4099731445312,
 995.3300170898438,
 975.25,
 996.4199829101562,
 994.0,
 975.2999877929688,
 875.0,
 877.3599853515625,
 821.7000122070312,
 870.0,
 848.030029296875,
 888.5900268554688,
 885.280029296875,
 857.7000122070312,
 843.1099853515625,
 781.1500244140625,
 774.25,
 727.2000122070312,
 680.0,
 751.5700073242188,
 719.0900268554688,
 728.8499755859375,
 700.8099975585938,
 694.1099853515625,
 633.0,
 638.0599975585938,
 620.5700073242188,
 623.010009765625,
 653.6599731445312,
 720.530029296875,
 734.22998046875,
 730.9199829101562,
 726.2000122070312,
 700.25,
 703.0499877929688,
 690.280029296875,
 717.530029296875,
 717.97998046875,
 683.739990234375,
 644.0499877929688,
 635.2100219726562,
 654.4500122070312,
 626.0800170898438,
 639.5900268554688,
 673.0,
 701.47998046875,
 685.9099731445312,
 708.260009765625,
 727.7000122070312,
 697.030029296875,
 666.8200073242188,
 656.5900268554688,
 666.3599853515625,
 648.5,
 681.5599975585938,
 696.6300048828125,
 723.47998046875,
 700.8800048828125,
 685.1099853515625,
 675.0999755859375,
 688.0]

In [8]:
df = pdr.get_data_yahoo('TSLA', 2022, 2023)
times = df.index
datas = []  # time
for t in times:
    datas.append(t)
df_highest = df['High'].to_list()
df_lowest = df['Low'].to_list()
df_open = df['Open'].to_list()
df_Close = df['Close'].to_list()
df_vol = df['Volume'].to_list()
df_adj = df['Adj Close'].to_list()
values = []
for i in range(len(df_highest)):
    values.append([datas[i], round(df_highest[i], 2), round(df_lowest[i], 2),
                   round(df_open[i], 2), round(df_Close[i], 2), round(df_vol[i], 2), round(df_adj[i], 2)])
values

[[Timestamp('2021-12-31 00:00:00'),
  1082.0,
  1054.59,
  1073.44,
  1056.78,
  13577900,
  1056.78],
 [Timestamp('2022-01-03 00:00:00'),
  1201.07,
  1136.04,
  1147.75,
  1199.78,
  34643800,
  1199.78],
 [Timestamp('2022-01-04 00:00:00'),
  1208.0,
  1123.05,
  1189.55,
  1149.59,
  33416100,
  1149.59],
 [Timestamp('2022-01-05 00:00:00'),
  1170.34,
  1081.01,
  1146.65,
  1088.12,
  26706600,
  1088.12],
 [Timestamp('2022-01-06 00:00:00'),
  1088.0,
  1020.5,
  1077.0,
  1064.7,
  30112200,
  1064.7],
 [Timestamp('2022-01-07 00:00:00'),
  1080.93,
  1010.0,
  1080.37,
  1026.96,
  28054900,
  1026.96],
 [Timestamp('2022-01-10 00:00:00'),
  1059.1,
  980.0,
  1000.0,
  1058.12,
  30605000,
  1058.12],
 [Timestamp('2022-01-11 00:00:00'),
  1075.85,
  1038.82,
  1053.67,
  1064.4,
  22021100,
  1064.4],
 [Timestamp('2022-01-12 00:00:00'),
  1114.84,
  1072.59,
  1078.85,
  1106.22,
  27913000,
  1106.22],
 [Timestamp('2022-01-13 00:00:00'),
  1115.6,
  1026.54,
  1109.07,
  1031.56,
  32403300,
  1031.56],
 [Timestamp('2022-01-14 00:00:00'),
  1052.0,
  1013.38,
  1019.88,
  1049.61,
  24308100,
  1049.61],
 [Timestamp('2022-01-18 00:00:00'),
  1070.79,
  1016.06,
  1026.61,
  1030.51,
  22247800,
  1030.51],
 [Timestamp('2022-01-19 00:00:00'),
  1054.67,
  995.0,
  1041.71,
  995.65,
  25147500,
  995.65],
 [Timestamp('2022-01-20 00:00:00'),
  1041.66,
  994.0,
  1009.73,
  996.27,
  23496200,
  996.27],
 [Timestamp('2022-01-21 00:00:00'),
  1004.55,
  940.5,
  996.34,
  943.9,
  34472000,
  943.9],
 [Timestamp('2022-01-24 00:00:00'),
  933.51,
  851.47,
  904.76,
  930.0,
  50521900,
  930.0],
 [Timestamp('2022-01-25 00:00:00'),
  951.26,
  903.21,
  914.2,
  918.4,
  28865300,
  918.4],
 [Timestamp('2022-01-26 00:00:00'),
  987.69,
  906.0,
  952.43,
  937.41,
  34955800,
  937.41],
 [Timestamp('2022-01-27 00:00:00'),
  935.39,
  829.0,
  933.36,
  829.1,
  49036500,
  829.1],
 [Timestamp('2022-01-28 00:00:00'),
  857.5,
  792.01,
  831.56,
  846.35,
  44929700,
  846.35],
 [Timestamp('2022-01-31 00:00:00'),
  937.99,
  862.05,
  872.71,
  936.72,
  34812000,
  936.72],
 [Timestamp('2022-02-01 00:00:00'),
  943.7,
  905.0,
  935.21,
  931.25,
  24379400,
  931.25],
 [Timestamp('2022-02-02 00:00:00'),
  931.5,
  889.41,
  928.18,
  905.66,
  22264300,
  905.66],
 [Timestamp('2022-02-03 00:00:00'),
  937.0,
  880.52,
  882.0,
  891.14,
  26285200,
  891.14],
 [Timestamp('2022-02-04 00:00:00'),
  936.5,
  881.17,
  897.22,
  923.32,
  24541800,
  923.32],
 [Timestamp('2022-02-07 00:00:00'),
  947.77,
  902.71,
  923.79,
  907.34,
  20331500,
  907.34],
 [Timestamp('2022-02-08 00:00:00'),
  926.29,
  894.8,
  905.53,
  922.0,
  16909700,
  922.0],
 [Timestamp('2022-02-09 00:00:00'),
  946.27,
  920.0,
  935.0,
  932.0,
  17419800,
  932.0],
 [Timestamp('2022-02-10 00:00:00'),
  943.81,
  896.7,
  908.37,
  904.55,
  22042300,
  904.55],
 [Timestamp('2022-02-11 00:00:00'),
  915.96,
  850.7,
  909.63,
  860.0,
  26548600,
  860.0],
 [Timestamp('2022-02-14 00:00:00'),
  898.88,
  853.15,
  861.57,
  875.76,
  22585500,
  875.76],
 [Timestamp('2022-02-15 00:00:00'),
  923.0,
  893.38,
  900.0,
  922.43,
  19095400,
  922.43],
 [Timestamp('2022-02-16 00:00:00'),
  926.43,
  901.21,
  914.05,
  923.39,
  17098100,
  923.39],
 [Timestamp('2022-02-17 00:00:00'),
  918.5,
  874.1,
  913.26,
  876.35,
  18392800,
  876.35],
 [Timestamp('2022-02-18 00:00:00'),
  886.87,
  837.61,
  886.0,
  856.98,
  22833900,
  856.98],
 [Timestamp('2022-02-22 00:00:00'),
  856.73,
  801.1,
  834.13,
  821.53,
  27762700,
  821.53],
 [Timestamp('2022-02-23 00:00:00'),
  835.3,
  760.56,
  830.43,
  764.04,
  31752300,
  764.04],
 [Timestamp('2022-02-24 00:00:00'),
  802.48,
  700.0,
  700.39,
  800.77,
  45107400,
  800.77],
 [Timestamp('2022-02-25 00:00:00'),
  819.5,
  782.4,
  809.23,
  809.87,
  25355900,
  809.87],
 [Timestamp('2022-02-28 00:00:00'),
  876.86,
  814.71,
  815.01,
  870.43,
  33002300,
  870.43],
 [Timestamp('2022-03-01 00:00:00'),
  889.88,
  853.78,
  869.68,
  864.37,
  24922300,
  864.37],
 [Timestamp('2022-03-02 00:00:00'),
  886.48,
  844.27,
  872.13,
  879.89,
  24881100,
  879.89],
 [Timestamp('2022-03-03 00:00:00'),
  886.44,
  832.6,
  878.77,
  839.29,
  20541200,
  839.29],
 [Timestamp('2022-03-04 00:00:00'),
  855.65,
  825.16,
  849.1,
  838.29,
  22333200,
  838.29],
 [Timestamp('2022-03-07 00:00:00'),
  866.14,
  804.57,
  856.3,
  804.58,
  24164700,
  804.58],
 [Timestamp('2022-03-08 00:00:00'),
  849.99,
  782.17,
  795.53,
  824.4,
  26799700,
  824.4],
 [Timestamp('2022-03-09 00:00:00'),
  860.56,
  832.01,
  839.48,
  858.97,
  19728000,
  858.97],
 [Timestamp('2022-03-10 00:00:00'),
  854.45,
  810.36,
  851.45,
  838.3,
  19549500,
  838.3],
 [Timestamp('2022-03-11 00:00:00'),
  843.8,
  793.77,
  840.2,
  795.35,
  22345700,
  795.35],
 [Timestamp('2022-03-14 00:00:00'),
  800.7,
  756.04,
  780.61,
  766.37,
  23717400,
  766.37],
 [Timestamp('2022-03-15 00:00:00'),
  805.57,
  756.57,
  775.27,
  801.89,
  22280400,
  801.89],
 [Timestamp('2022-03-16 00:00:00'),
  842.0,
  802.26,
  809.0,
  840.23,
  28009600,
  840.23],
 [Timestamp('2022-03-17 00:00:00'),
  875.0,
  825.72,
  830.99,
  871.6,
  22194300,
  871.6],
 [Timestamp('2022-03-18 00:00:00'),
  907.85,
  867.39,
  874.49,
  905.39,
  33471400,
  905.39],
 [Timestamp('2022-03-21 00:00:00'),
  942.85,
  907.09,
  914.98,
  921.16,
  27327200,
  921.16],
 [Timestamp('2022-03-22 00:00:00'),
  997.86,
  921.75,
  930.0,
  993.98,
  35289500,
  993.98],
 [Timestamp('2022-03-23 00:00:00'),
  1040.7,
  976.4,
  979.94,
  999.11,
  40225400,
  999.11],
 [Timestamp('2022-03-24 00:00:00'),
  1024.49,
  988.8,
  1009.73,
  1013.92,
  22973600,
  1013.92],
 [Timestamp('2022-03-25 00:00:00'),
  1021.8,
  997.32,
  1008.0,
  1010.64,
  20677200,
  1010.64],
 [Timestamp('2022-03-28 00:00:00'),
  1097.88,
  1053.6,
  1065.1,
  1091.84,
  34168700,
  1091.84],
 [Timestamp('2022-03-29 00:00:00'),
  1114.77,
  1073.11,
  1107.99,
  1099.57,
  24538300,
  1099.57],
 [Timestamp('2022-03-30 00:00:00'),
  1113.95,
  1084.0,
  1091.17,
  1093.99,
  19955000,
  1093.99],
 [Timestamp('2022-03-31 00:00:00'),
  1103.14,
  1076.64,
  1094.57,
  1077.6,
  16330900,
  1077.6],
 [Timestamp('2022-04-01 00:00:00'),
  1094.75,
  1066.64,
  1081.15,
  1084.59,
  18087700,
  1084.59],
 [Timestamp('2022-04-04 00:00:00'),
  1149.91,
  1072.53,
  1089.38,
  1145.45,
  27345300,
  1145.45],
 [Timestamp('2022-04-05 00:00:00'),
  1152.87,
  1087.3,
  1136.3,
  1091.26,
  26691700,
  1091.26],
 [Timestamp('2022-04-06 00:00:00'),
  1079.0,
  1027.7,
  1073.47,
  1045.76,
  29782800,
  1045.76],
 [Timestamp('2022-04-07 00:00:00'),
  1076.59,
  1021.54,
  1052.39,
  1057.26,
  26482400,
  1057.26],
 [Timestamp('2022-04-08 00:00:00'),
  1048.44,
  1022.44,
  1043.21,
  1025.49,
  18337900,
  1025.49],
 [Timestamp('2022-04-11 00:00:00'),
  1008.47,
  974.64,
  980.4,
  975.93,
  19785700,
  975.93],
 [Timestamp('2022-04-12 00:00:00'),
  1021.19,
  976.6,
  997.64,
  986.95,
  21992000,
  986.95],
 [Timestamp('2022-04-13 00:00:00'),
  1026.24,
  973.1,
  981.08,
  1022.37,
  18373700,
  1022.37],
 [Timestamp('2022-04-14 00:00:00'),
  1012.71,
  982.19,
  999.29,
  985.0,
  19474100,
  985.0],
 [Timestamp('2022-04-18 00:00:00'),
  1014.92,
  973.41,
  989.03,
  1004.29,
  17238400,
  1004.29],
 [Timestamp('2022-04-19 00:00:00'),
  1034.94,
  995.33,
  1005.06,
  1028.15,
  16615900,
  1028.15],
 [Timestamp('2022-04-20 00:00:00'),
  1034.0,
  975.25,
  1030.0,
  977.2,
  23570400,
  977.2],
 [Timestamp('2022-04-21 00:00:00'),
  1092.22,
  996.42,
  1074.73,
  1008.78,
  35138800,
  1008.78],
 [Timestamp('2022-04-22 00:00:00'),
  1034.85,
  994.0,
  1014.91,
  1005.05,
  23232200,
  1005.05],
 [Timestamp('2022-04-25 00:00:00'),
  1008.62,
  975.3,
  978.97,
  998.02,
  22780400,
  998.02],
 [Timestamp('2022-04-26 00:00:00'),
  1000.0,
  875.0,
  995.43,
  876.42,
  45377900,
  876.42],
 [Timestamp('2022-04-27 00:00:00'),
  918.0,
  877.36,
  898.58,
  881.51,
  25652100,
  881.51],
 [Timestamp('2022-04-28 00:00:00'),
  900.0,
  821.7,
  899.98,
  877.51,
  41649500,
  877.51],
 [Timestamp('2022-04-29 00:00:00'),
  934.4,
  870.0,
  902.25,
  870.76,
  29377700,
  870.76],
 [Timestamp('2022-05-02 00:00:00'),
  906.36,
  848.03,
  860.77,
  902.94,
  25260500,
  902.94],
 [Timestamp('2022-05-03 00:00:00'),
  924.08,
  888.59,
  903.18,
  909.25,
  21236500,
  909.25],
 [Timestamp('2022-05-04 00:00:00'),
  955.5,
  885.28,
  903.94,
  952.62,
  27214600,
  952.62],
 [Timestamp('2022-05-05 00:00:00'),
  945.6,
  857.7,
  939.02,
  873.28,
  30839700,
  873.28],
 [Timestamp('2022-05-06 00:00:00'),
  888.0,
  843.11,
  887.0,
  865.65,
  24301000,
  865.65],
 [Timestamp('2022-05-09 00:00:00'),
  845.63,
  781.15,
  836.45,
  787.11,
  30270100,
  787.11],
 [Timestamp('2022-05-10 00:00:00'),
  825.36,
  774.25,
  819.31,
  800.04,
  28133900,
  800.04],
 [Timestamp('2022-05-11 00:00:00'),
  809.77,
  727.2,
  795.0,
  734.0,
  32408200,
  734.0],
 [Timestamp('2022-05-12 00:00:00'),
  759.66,
  680.0,
  701.0,
  728.0,
  46771000,
  728.0],
 [Timestamp('2022-05-13 00:00:00'),
  787.35,
  751.57,
  773.48,
  769.59,
  30716900,
  769.59],
 [Timestamp('2022-05-16 00:00:00'),
  769.76,
  719.09,
  767.16,
  724.37,
  28699500,
  724.37],
 [Timestamp('2022-05-17 00:00:00'),
  764.48,
  728.85,
  747.36,
  761.61,
  26745400,
  761.61],
 [Timestamp('2022-05-18 00:00:00'),
  760.5,
  700.81,
  744.52,
  709.81,
  29270600,
  709.81],
 [Timestamp('2022-05-19 00:00:00'),
  734.0,
  694.11,
  707.0,
  709.42,
  30098900,
  709.42],
 [Timestamp('2022-05-20 00:00:00'),
  721.58,
  633.0,
  713.99,
  663.9,
  48324400,
  663.9],
 [Timestamp('2022-05-23 00:00:00'),
  679.96,
  638.06,
  655.02,
  674.9,
  29634500,
  674.9],
 [Timestamp('2022-05-24 00:00:00'),
  653.92,
  620.57,
  653.53,
  628.16,
  29697500,
  628.16],
 [Timestamp('2022-05-25 00:00:00'),
  669.32,
  623.01,
  623.85,
  658.8,
  30713100,
  658.8],
 [Timestamp('2022-05-26 00:00:00'),
  718.67,
  653.66,
  661.42,
  707.73,
  35334400,
  707.73],
 [Timestamp('2022-05-27 00:00:00'),
  759.8,
  720.53,
  723.25,
  759.63,
  29765000,
  759.63],
 [Timestamp('2022-05-31 00:00:00'),
  778.8,
  734.23,
  773.84,
  758.26,
  33971500,
  758.26],
 [Timestamp('2022-06-01 00:00:00'),
  771.98,
  730.92,
  755.16,
  740.37,
  25749300,
  740.37],
 [Timestamp('2022-06-02 00:00:00'),
  792.63,
  726.2,
  732.47,
  775.0,
  31157700,
  775.0],
 [Timestamp('2022-06-03 00:00:00'),
  743.39,
  700.25,
  729.68,
  703.55,
  37348100,
  703.55],
 [Timestamp('2022-06-06 00:00:00'),
  734.6,
  703.05,
  733.06,
  714.84,
  28068200,
  714.84],
 [Timestamp('2022-06-07 00:00:00'),
  719.99,
  690.28,
  702.0,
  716.66,
  24269500,
  716.66],
 [Timestamp('2022-06-08 00:00:00'),
  749.89,
  717.53,
  720.26,
  725.6,
  25403500,
  725.6],
 [Timestamp('2022-06-09 00:00:00'),
  766.64,
  717.98,
  748.02,
  719.12,
  32163800,
  719.12],
 [Timestamp('2022-06-10 00:00:00'),
  718.5,
  683.74,
  705.47,
  696.69,
  32512200,
  696.69],
 [Timestamp('2022-06-13 00:00:00'),
  679.9,
  644.05,
  669.5,
  647.21,
  34255800,
  647.21],
 [Timestamp('2022-06-14 00:00:00'),
  678.99,
  635.21,
  654.86,
  662.67,
  32662900,
  662.67],
 [Timestamp('2022-06-15 00:00:00'),
  706.99,
  654.45,
  662.75,
  699.0,
  39710600,
  699.0],
 [Timestamp('2022-06-16 00:00:00'),
  675.5,
  626.08,
  668.21,
  639.3,
  35796900,
  639.3],
 [Timestamp('2022-06-17 00:00:00'),
  662.91,
  639.59,
  640.3,
  650.28,
  30810900,
  650.28],
 [Timestamp('2022-06-21 00:00:00'),
  730.73,
  673.0,
  673.81,
  711.11,
  40931000,
  711.11],
 [Timestamp('2022-06-22 00:00:00'),
  740.5,
  701.48,
  703.51,
  708.26,
  33702500,
  708.26],
 [Timestamp('2022-06-23 00:00:00'),
  717.95,
  685.91,
  713.72,
  705.21,
  34734200,
  705.21],
 [Timestamp('2022-06-24 00:00:00'),
  738.2,
  708.26,
  712.41,
  737.12,
  31866500,
  737.12],
 [Timestamp('2022-06-27 00:00:00'),
  756.21,
  727.7,
  748.1,
  734.76,
  29726100,
  734.76],
 [Timestamp('2022-06-28 00:00:00'),
  749.91,
  697.03,
  733.45,
  697.99,
  30130400,
  697.99],
 [Timestamp('2022-06-29 00:00:00'),
  693.52,
  666.82,
  691.5,
  685.47,
  27632400,
  685.47],
 [Timestamp('2022-06-30 00:00:00'),
  688.37,
  656.59,
  673.53,
  673.42,
  31533500,
  673.42],
 [Timestamp('2022-07-01 00:00:00'),
  690.69,
  666.36,
  681.0,
  681.79,
  24781500,
  681.79],
 [Timestamp('2022-07-05 00:00:00'),
  699.44,
  648.5,
  669.0,
  699.2,
  28193700,
  699.2],
 [Timestamp('2022-07-06 00:00:00'),
  703.69,
  681.56,
  692.34,
  695.2,
  23951200,
  695.2],
 [Timestamp('2022-07-07 00:00:00'),
  736.09,
  696.63,
  701.76,
  733.63,
  27310200,
  733.63],
 [Timestamp('2022-07-08 00:00:00'),
  764.94,
  723.48,
  727.0,
  752.29,
  33343700,
  752.29],
 [Timestamp('2022-07-11 00:00:00'),
  759.19,
  700.88,
  756.31,
  703.03,
  33080400,
  703.03],
 [Timestamp('2022-07-12 00:00:00'),
  719.32,
  685.11,
  710.54,
  699.21,
  29310300,
  699.21],
 [Timestamp('2022-07-13 00:00:00'),
  726.18,
  675.1,
  676.5,
  711.12,
  32651500,
  711.12],
 [Timestamp('2022-07-14 00:00:00'),
  715.96,
  688.0,
  704.69,
  714.94,
  26069500,
  714.94]]

In [9]:
def time_test():
    times = df.index
    datas = []
    for t in times:
        print(t)
        datas.append(t)
    return datas

In [10]:
time_test()

2021-12-31 00:00:00
2022-01-03 00:00:00
2022-01-04 00:00:00
2022-01-05 00:00:00
2022-01-06 00:00:00
2022-01-07 00:00:00
2022-01-10 00:00:00
2022-01-11 00:00:00
2022-01-12 00:00:00
2022-01-13 00:00:00
2022-01-14 00:00:00
2022-01-18 00:00:00
2022-01-19 00:00:00
2022-01-20 00:00:00
2022-01-21 00:00:00
2022-01-24 00:00:00
2022-01-25 00:00:00
2022-01-26 00:00:00
2022-01-27 00:00:00
2022-01-28 00:00:00
2022-01-31 00:00:00
2022-02-01 00:00:00
2022-02-02 00:00:00
2022-02-03 00:00:00
2022-02-04 00:00:00
2022-02-07 00:00:00
2022-02-08 00:00:00
2022-02-09 00:00:00
2022-02-10 00:00:00
2022-02-11 00:00:00
2022-02-14 00:00:00
2022-02-15 00:00:00
2022-02-16 00:00:00
2022-02-17 00:00:00
2022-02-18 00:00:00
2022-02-22 00:00:00
2022-02-23 00:00:00
2022-02-24 00:00:00
2022-02-25 00:00:00
2022-02-28 00:00:00
2022-03-01 00:00:00
2022-03-02 00:00:00
2022-03-03 00:00:00
2022-03-04 00:00:00
2022-03-07 00:00:00
2022-03-08 00:00:00
2022-03-09 00:00:00
2022-03-10 00:00:00
2022-03-11 00:00:00
2022-03-14 00:00:00
2022-03-15 00:00:00
2022-03-16 00:00:00
2022-03-17 00:00:00
2022-03-18 00:00:00
2022-03-21 00:00:00
2022-03-22 00:00:00
2022-03-23 00:00:00
2022-03-24 00:00:00
2022-03-25 00:00:00
2022-03-28 00:00:00
2022-03-29 00:00:00
2022-03-30 00:00:00
2022-03-31 00:00:00
2022-04-01 00:00:00
2022-04-04 00:00:00
2022-04-05 00:00:00
2022-04-06 00:00:00
2022-04-07 00:00:00
2022-04-08 00:00:00
2022-04-11 00:00:00
2022-04-12 00:00:00
2022-04-13 00:00:00
2022-04-14 00:00:00
2022-04-18 00:00:00
2022-04-19 00:00:00
2022-04-20 00:00:00
2022-04-21 00:00:00
2022-04-22 00:00:00
2022-04-25 00:00:00
2022-04-26 00:00:00
2022-04-27 00:00:00
2022-04-28 00:00:00
2022-04-29 00:00:00
2022-05-02 00:00:00
2022-05-03 00:00:00
2022-05-04 00:00:00
2022-05-05 00:00:00
2022-05-06 00:00:00
2022-05-09 00:00:00
2022-05-10 00:00:00
2022-05-11 00:00:00
2022-05-12 00:00:00
2022-05-13 00:00:00
2022-05-16 00:00:00
2022-05-17 00:00:00
2022-05-18 00:00:00
2022-05-19 00:00:00
2022-05-20 00:00:00
2022-05-23 00:00:00
2022-05-24 00:00:00
2022-05-25 00:00:00
2022-05-26 00:00:00
2022-05-27 00:00:00
2022-05-31 00:00:00
2022-06-01 00:00:00
2022-06-02 00:00:00
2022-06-03 00:00:00
2022-06-06 00:00:00
2022-06-07 00:00:00
2022-06-08 00:00:00
2022-06-09 00:00:00
2022-06-10 00:00:00
2022-06-13 00:00:00
2022-06-14 00:00:00
2022-06-15 00:00:00
2022-06-16 00:00:00
2022-06-17 00:00:00
2022-06-21 00:00:00
2022-06-22 00:00:00
2022-06-23 00:00:00
2022-06-24 00:00:00
2022-06-27 00:00:00
2022-06-28 00:00:00
2022-06-29 00:00:00
2022-06-30 00:00:00
2022-07-01 00:00:00
2022-07-05 00:00:00
2022-07-06 00:00:00
2022-07-07 00:00:00
2022-07-08 00:00:00
2022-07-11 00:00:00
2022-07-12 00:00:00
2022-07-13 00:00:00
2022-07-14 00:00:00

[Timestamp('2021-12-31 00:00:00'),
 Timestamp('2022-01-03 00:00:00'),
 Timestamp('2022-01-04 00:00:00'),
 Timestamp('2022-01-05 00:00:00'),
 Timestamp('2022-01-06 00:00:00'),
 Timestamp('2022-01-07 00:00:00'),
 Timestamp('2022-01-10 00:00:00'),
 Timestamp('2022-01-11 00:00:00'),
 Timestamp('2022-01-12 00:00:00'),
 Timestamp('2022-01-13 00:00:00'),
 Timestamp('2022-01-14 00:00:00'),
 Timestamp('2022-01-18 00:00:00'),
 Timestamp('2022-01-19 00:00:00'),
 Timestamp('2022-01-20 00:00:00'),
 Timestamp('2022-01-21 00:00:00'),
 Timestamp('2022-01-24 00:00:00'),
 Timestamp('2022-01-25 00:00:00'),
 Timestamp('2022-01-26 00:00:00'),
 Timestamp('2022-01-27 00:00:00'),
 Timestamp('2022-01-28 00:00:00'),
 Timestamp('2022-01-31 00:00:00'),
 Timestamp('2022-02-01 00:00:00'),
 Timestamp('2022-02-02 00:00:00'),
 Timestamp('2022-02-03 00:00:00'),
 Timestamp('2022-02-04 00:00:00'),
 Timestamp('2022-02-07 00:00:00'),
 Timestamp('2022-02-08 00:00:00'),
 Timestamp('2022-02-09 00:00:00'),
 Timestamp('2022-02-10 00:00:00'),
 Timestamp('2022-02-11 00:00:00'),
 Timestamp('2022-02-14 00:00:00'),
 Timestamp('2022-02-15 00:00:00'),
 Timestamp('2022-02-16 00:00:00'),
 Timestamp('2022-02-17 00:00:00'),
 Timestamp('2022-02-18 00:00:00'),
 Timestamp('2022-02-22 00:00:00'),
 Timestamp('2022-02-23 00:00:00'),
 Timestamp('2022-02-24 00:00:00'),
 Timestamp('2022-02-25 00:00:00'),
 Timestamp('2022-02-28 00:00:00'),
 Timestamp('2022-03-01 00:00:00'),
 Timestamp('2022-03-02 00:00:00'),
 Timestamp('2022-03-03 00:00:00'),
 Timestamp('2022-03-04 00:00:00'),
 Timestamp('2022-03-07 00:00:00'),
 Timestamp('2022-03-08 00:00:00'),
 Timestamp('2022-03-09 00:00:00'),
 Timestamp('2022-03-10 00:00:00'),
 Timestamp('2022-03-11 00:00:00'),
 Timestamp('2022-03-14 00:00:00'),
 Timestamp('2022-03-15 00:00:00'),
 Timestamp('2022-03-16 00:00:00'),
 Timestamp('2022-03-17 00:00:00'),
 Timestamp('2022-03-18 00:00:00'),
 Timestamp('2022-03-21 00:00:00'),
 Timestamp('2022-03-22 00:00:00'),
 Timestamp('2022-03-23 00:00:00'),
 Timestamp('2022-03-24 00:00:00'),
 Timestamp('2022-03-25 00:00:00'),
 Timestamp('2022-03-28 00:00:00'),
 Timestamp('2022-03-29 00:00:00'),
 Timestamp('2022-03-30 00:00:00'),
 Timestamp('2022-03-31 00:00:00'),
 Timestamp('2022-04-01 00:00:00'),
 Timestamp('2022-04-04 00:00:00'),
 Timestamp('2022-04-05 00:00:00'),
 Timestamp('2022-04-06 00:00:00'),
 Timestamp('2022-04-07 00:00:00'),
 Timestamp('2022-04-08 00:00:00'),
 Timestamp('2022-04-11 00:00:00'),
 Timestamp('2022-04-12 00:00:00'),
 Timestamp('2022-04-13 00:00:00'),
 Timestamp('2022-04-14 00:00:00'),
 Timestamp('2022-04-18 00:00:00'),
 Timestamp('2022-04-19 00:00:00'),
 Timestamp('2022-04-20 00:00:00'),
 Timestamp('2022-04-21 00:00:00'),
 Timestamp('2022-04-22 00:00:00'),
 Timestamp('2022-04-25 00:00:00'),
 Timestamp('2022-04-26 00:00:00'),
 Timestamp('2022-04-27 00:00:00'),
 Timestamp('2022-04-28 00:00:00'),
 Timestamp('2022-04-29 00:00:00'),
 Timestamp('2022-05-02 00:00:00'),
 Timestamp('2022-05-03 00:00:00'),
 Timestamp('2022-05-04 00:00:00'),
 Timestamp('2022-05-05 00:00:00'),
 Timestamp('2022-05-06 00:00:00'),
 Timestamp('2022-05-09 00:00:00'),
 Timestamp('2022-05-10 00:00:00'),
 Timestamp('2022-05-11 00:00:00'),
 Timestamp('2022-05-12 00:00:00'),
 Timestamp('2022-05-13 00:00:00'),
 Timestamp('2022-05-16 00:00:00'),
 Timestamp('2022-05-17 00:00:00'),
 Timestamp('2022-05-18 00:00:00'),
 Timestamp('2022-05-19 00:00:00'),
 Timestamp('2022-05-20 00:00:00'),
 Timestamp('2022-05-23 00:00:00'),
 Timestamp('2022-05-24 00:00:00'),
 Timestamp('2022-05-25 00:00:00'),
 Timestamp('2022-05-26 00:00:00'),
 Timestamp('2022-05-27 00:00:00'),
 Timestamp('2022-05-31 00:00:00'),
 Timestamp('2022-06-01 00:00:00'),
 Timestamp('2022-06-02 00:00:00'),
 Timestamp('2022-06-03 00:00:00'),
 Timestamp('2022-06-06 00:00:00'),
 Timestamp('2022-06-07 00:00:00'),
 Timestamp('2022-06-08 00:00:00'),
 Timestamp('2022-06-09 00:00:00'),
 Timestamp('2022-06-10 00:00:00'),
 Timestamp('2022-06-13 00:00:00'),
 Timestamp('2022-06-14 00:00:00'),
 Timestamp('2022-06-15 00:00:00'),
 Timestamp('2022-06-16 00:00:00'),
 Timestamp('2022-06-17 00:00:00'),
 Timestamp('2022-06-21 00:00:00'),
 Timestamp('2022-06-22 00:00:00'),
 Timestamp('2022-06-23 00:00:00'),
 Timestamp('2022-06-24 00:00:00'),
 Timestamp('2022-06-27 00:00:00'),
 Timestamp('2022-06-28 00:00:00'),
 Timestamp('2022-06-29 00:00:00'),
 Timestamp('2022-06-30 00:00:00'),
 Timestamp('2022-07-01 00:00:00'),
 Timestamp('2022-07-05 00:00:00'),
 Timestamp('2022-07-06 00:00:00'),
 Timestamp('2022-07-07 00:00:00'),
 Timestamp('2022-07-08 00:00:00'),
 Timestamp('2022-07-11 00:00:00'),
 Timestamp('2022-07-12 00:00:00'),
 Timestamp('2022-07-13 00:00:00'),
 Timestamp('2022-07-14 00:00:00')]

In [11]:
df.index.astype(str)

Index(['2021-12-31', '2022-01-03', '2022-01-04', '2022-01-05', '2022-01-06',
       '2022-01-07', '2022-01-10', '2022-01-11', '2022-01-12', '2022-01-13',
       ...
       '2022-06-30', '2022-07-01', '2022-07-05', '2022-07-06', '2022-07-07',
       '2022-07-08', '2022-07-11', '2022-07-12', '2022-07-13', '2022-07-14'],
      dtype='object', name='Date', length=134)

In [12]:
def get_US_stock():
    df = pdr.get_data_yahoo('TSLA', 2022, 2023)
    times = df.index.astype(str)
    columns = [	'Date', 'High'	, 'Low'	, 'Open'	,
                'Close'	, 'Volume'	, 'Adj Close']
    datas = []  # time
    for t in times:
        datas.append(t)
    df_highest = df['High'].to_list()
    df_lowest = df['Low'].to_list()
    df_open = df['Open'].to_list()
    df_Close = df['Close'].to_list()
    df_vol = df['Volume'].to_list()
    df_adj = df['Adj Close'].to_list()
    values = []
    for i in range(len(df_highest)):
        values.append([datas[i], round(df_highest[i], 2), round(df_lowest[i], 2),
                       round(df_open[i], 2), round(df_Close[i], 2), round(df_vol[i], 2), round(df_adj[i], 2)])
    return columns, values

In [13]:
get_US_stock()

(['Date', 'High', 'Low', 'Open', 'Close', 'Volume', 'Adj Close'],
 [['2021-12-31', 1082.0, 1054.59, 1073.44, 1056.78, 13577900, 1056.78],
  ['2022-01-03', 1201.07, 1136.04, 1147.75, 1199.78, 34643800, 1199.78],
  ['2022-01-04', 1208.0, 1123.05, 1189.55, 1149.59, 33416100, 1149.59],
  ['2022-01-05', 1170.34, 1081.01, 1146.65, 1088.12, 26706600, 1088.12],
  ['2022-01-06', 1088.0, 1020.5, 1077.0, 1064.7, 30112200, 1064.7],
  ['2022-01-07', 1080.93, 1010.0, 1080.37, 1026.96, 28054900, 1026.96],
  ['2022-01-10', 1059.1, 980.0, 1000.0, 1058.12, 30605000, 1058.12],
  ['2022-01-11', 1075.85, 1038.82, 1053.67, 1064.4, 22021100, 1064.4],
  ['2022-01-12', 1114.84, 1072.59, 1078.85, 1106.22, 27913000, 1106.22],
  ['2022-01-13', 1115.6, 1026.54, 1109.07, 1031.56, 32403300, 1031.56],
  ['2022-01-14', 1052.0, 1013.38, 1019.88, 1049.61, 24308100, 1049.61],
  ['2022-01-18', 1070.79, 1016.06, 1026.61, 1030.51, 22247800, 1030.51],
  ['2022-01-19', 1054.67, 995.0, 1041.71, 995.65, 25147500, 995.65],
  ['2022-01-20', 1041.66, 994.0, 1009.73, 996.27, 23496200, 996.27],
  ['2022-01-21', 1004.55, 940.5, 996.34, 943.9, 34472000, 943.9],
  ['2022-01-24', 933.51, 851.47, 904.76, 930.0, 50521900, 930.0],
  ['2022-01-25', 951.26, 903.21, 914.2, 918.4, 28865300, 918.4],
  ['2022-01-26', 987.69, 906.0, 952.43, 937.41, 34955800, 937.41],
  ['2022-01-27', 935.39, 829.0, 933.36, 829.1, 49036500, 829.1],
  ['2022-01-28', 857.5, 792.01, 831.56, 846.35, 44929700, 846.35],
  ['2022-01-31', 937.99, 862.05, 872.71, 936.72, 34812000, 936.72],
  ['2022-02-01', 943.7, 905.0, 935.21, 931.25, 24379400, 931.25],
  ['2022-02-02', 931.5, 889.41, 928.18, 905.66, 22264300, 905.66],
  ['2022-02-03', 937.0, 880.52, 882.0, 891.14, 26285200, 891.14],
  ['2022-02-04', 936.5, 881.17, 897.22, 923.32, 24541800, 923.32],
  ['2022-02-07', 947.77, 902.71, 923.79, 907.34, 20331500, 907.34],
  ['2022-02-08', 926.29, 894.8, 905.53, 922.0, 16909700, 922.0],
  ['2022-02-09', 946.27, 920.0, 935.0, 932.0, 17419800, 932.0],
  ['2022-02-10', 943.81, 896.7, 908.37, 904.55, 22042300, 904.55],
  ['2022-02-11', 915.96, 850.7, 909.63, 860.0, 26548600, 860.0],
  ['2022-02-14', 898.88, 853.15, 861.57, 875.76, 22585500, 875.76],
  ['2022-02-15', 923.0, 893.38, 900.0, 922.43, 19095400, 922.43],
  ['2022-02-16', 926.43, 901.21, 914.05, 923.39, 17098100, 923.39],
  ['2022-02-17', 918.5, 874.1, 913.26, 876.35, 18392800, 876.35],
  ['2022-02-18', 886.87, 837.61, 886.0, 856.98, 22833900, 856.98],
  ['2022-02-22', 856.73, 801.1, 834.13, 821.53, 27762700, 821.53],
  ['2022-02-23', 835.3, 760.56, 830.43, 764.04, 31752300, 764.04],
  ['2022-02-24', 802.48, 700.0, 700.39, 800.77, 45107400, 800.77],
  ['2022-02-25', 819.5, 782.4, 809.23, 809.87, 25355900, 809.87],
  ['2022-02-28', 876.86, 814.71, 815.01, 870.43, 33002300, 870.43],
  ['2022-03-01', 889.88, 853.78, 869.68, 864.37, 24922300, 864.37],
  ['2022-03-02', 886.48, 844.27, 872.13, 879.89, 24881100, 879.89],
  ['2022-03-03', 886.44, 832.6, 878.77, 839.29, 20541200, 839.29],
  ['2022-03-04', 855.65, 825.16, 849.1, 838.29, 22333200, 838.29],
  ['2022-03-07', 866.14, 804.57, 856.3, 804.58, 24164700, 804.58],
  ['2022-03-08', 849.99, 782.17, 795.53, 824.4, 26799700, 824.4],
  ['2022-03-09', 860.56, 832.01, 839.48, 858.97, 19728000, 858.97],
  ['2022-03-10', 854.45, 810.36, 851.45, 838.3, 19549500, 838.3],
  ['2022-03-11', 843.8, 793.77, 840.2, 795.35, 22345700, 795.35],
  ['2022-03-14', 800.7, 756.04, 780.61, 766.37, 23717400, 766.37],
  ['2022-03-15', 805.57, 756.57, 775.27, 801.89, 22280400, 801.89],
  ['2022-03-16', 842.0, 802.26, 809.0, 840.23, 28009600, 840.23],
  ['2022-03-17', 875.0, 825.72, 830.99, 871.6, 22194300, 871.6],
  ['2022-03-18', 907.85, 867.39, 874.49, 905.39, 33471400, 905.39],
  ['2022-03-21', 942.85, 907.09, 914.98, 921.16, 27327200, 921.16],
  ['2022-03-22', 997.86, 921.75, 930.0, 993.98, 35289500, 993.98],
  ['2022-03-23', 1040.7, 976.4, 979.94, 999.11, 40225400, 999.11],
  ['2022-03-24', 1024.49, 988.8, 1009.73, 1013.92, 22973600, 1013.92],
  ['2022-03-25', 1021.8, 997.32, 1008.0, 1010.64, 20677200, 1010.64],
  ['2022-03-28', 1097.88, 1053.6, 1065.1, 1091.84, 34168700, 1091.84],
  ['2022-03-29', 1114.77, 1073.11, 1107.99, 1099.57, 24538300, 1099.57],
  ['2022-03-30', 1113.95, 1084.0, 1091.17, 1093.99, 19955000, 1093.99],
  ['2022-03-31', 1103.14, 1076.64, 1094.57, 1077.6, 16330900, 1077.6],
  ['2022-04-01', 1094.75, 1066.64, 1081.15, 1084.59, 18087700, 1084.59],
  ['2022-04-04', 1149.91, 1072.53, 1089.38, 1145.45, 27345300, 1145.45],
  ['2022-04-05', 1152.87, 1087.3, 1136.3, 1091.26, 26691700, 1091.26],
  ['2022-04-06', 1079.0, 1027.7, 1073.47, 1045.76, 29782800, 1045.76],
  ['2022-04-07', 1076.59, 1021.54, 1052.39, 1057.26, 26482400, 1057.26],
  ['2022-04-08', 1048.44, 1022.44, 1043.21, 1025.49, 18337900, 1025.49],
  ['2022-04-11', 1008.47, 974.64, 980.4, 975.93, 19785700, 975.93],
  ['2022-04-12', 1021.19, 976.6, 997.64, 986.95, 21992000, 986.95],
  ['2022-04-13', 1026.24, 973.1, 981.08, 1022.37, 18373700, 1022.37],
  ['2022-04-14', 1012.71, 982.19, 999.29, 985.0, 19474100, 985.0],
  ['2022-04-18', 1014.92, 973.41, 989.03, 1004.29, 17238400, 1004.29],
  ['2022-04-19', 1034.94, 995.33, 1005.06, 1028.15, 16615900, 1028.15],
  ['2022-04-20', 1034.0, 975.25, 1030.0, 977.2, 23570400, 977.2],
  ['2022-04-21', 1092.22, 996.42, 1074.73, 1008.78, 35138800, 1008.78],
  ['2022-04-22', 1034.85, 994.0, 1014.91, 1005.05, 23232200, 1005.05],
  ['2022-04-25', 1008.62, 975.3, 978.97, 998.02, 22780400, 998.02],
  ['2022-04-26', 1000.0, 875.0, 995.43, 876.42, 45377900, 876.42],
  ['2022-04-27', 918.0, 877.36, 898.58, 881.51, 25652100, 881.51],
  ['2022-04-28', 900.0, 821.7, 899.98, 877.51, 41649500, 877.51],
  ['2022-04-29', 934.4, 870.0, 902.25, 870.76, 29377700, 870.76],
  ['2022-05-02', 906.36, 848.03, 860.77, 902.94, 25260500, 902.94],
  ['2022-05-03', 924.08, 888.59, 903.18, 909.25, 21236500, 909.25],
  ['2022-05-04', 955.5, 885.28, 903.94, 952.62, 27214600, 952.62],
  ['2022-05-05', 945.6, 857.7, 939.02, 873.28, 30839700, 873.28],
  ['2022-05-06', 888.0, 843.11, 887.0, 865.65, 24301000, 865.65],
  ['2022-05-09', 845.63, 781.15, 836.45, 787.11, 30270100, 787.11],
  ['2022-05-10', 825.36, 774.25, 819.31, 800.04, 28133900, 800.04],
  ['2022-05-11', 809.77, 727.2, 795.0, 734.0, 32408200, 734.0],
  ['2022-05-12', 759.66, 680.0, 701.0, 728.0, 46771000, 728.0],
  ['2022-05-13', 787.35, 751.57, 773.48, 769.59, 30716900, 769.59],
  ['2022-05-16', 769.76, 719.09, 767.16, 724.37, 28699500, 724.37],
  ['2022-05-17', 764.48, 728.85, 747.36, 761.61, 26745400, 761.61],
  ['2022-05-18', 760.5, 700.81, 744.52, 709.81, 29270600, 709.81],
  ['2022-05-19', 734.0, 694.11, 707.0, 709.42, 30098900, 709.42],
  ['2022-05-20', 721.58, 633.0, 713.99, 663.9, 48324400, 663.9],
  ['2022-05-23', 679.96, 638.06, 655.02, 674.9, 29634500, 674.9],
  ['2022-05-24', 653.92, 620.57, 653.53, 628.16, 29697500, 628.16],
  ['2022-05-25', 669.32, 623.01, 623.85, 658.8, 30713100, 658.8],
  ['2022-05-26', 718.67, 653.66, 661.42, 707.73, 35334400, 707.73],
  ['2022-05-27', 759.8, 720.53, 723.25, 759.63, 29765000, 759.63],
  ['2022-05-31', 778.8, 734.23, 773.84, 758.26, 33971500, 758.26],
  ['2022-06-01', 771.98, 730.92, 755.16, 740.37, 25749300, 740.37],
  ['2022-06-02', 792.63, 726.2, 732.47, 775.0, 31157700, 775.0],
  ['2022-06-03', 743.39, 700.25, 729.68, 703.55, 37348100, 703.55],
  ['2022-06-06', 734.6, 703.05, 733.06, 714.84, 28068200, 714.84],
  ['2022-06-07', 719.99, 690.28, 702.0, 716.66, 24269500, 716.66],
  ['2022-06-08', 749.89, 717.53, 720.26, 725.6, 25403500, 725.6],
  ['2022-06-09', 766.64, 717.98, 748.02, 719.12, 32163800, 719.12],
  ['2022-06-10', 718.5, 683.74, 705.47, 696.69, 32512200, 696.69],
  ['2022-06-13', 679.9, 644.05, 669.5, 647.21, 34255800, 647.21],
  ['2022-06-14', 678.99, 635.21, 654.86, 662.67, 32662900, 662.67],
  ['2022-06-15', 706.99, 654.45, 662.75, 699.0, 39710600, 699.0],
  ['2022-06-16', 675.5, 626.08, 668.21, 639.3, 35796900, 639.3],
  ['2022-06-17', 662.91, 639.59, 640.3, 650.28, 30810900, 650.28],
  ['2022-06-21', 730.73, 673.0, 673.81, 711.11, 40931000, 711.11],
  ['2022-06-22', 740.5, 701.48, 703.51, 708.26, 33702500, 708.26],
  ['2022-06-23', 717.95, 685.91, 713.72, 705.21, 34734200, 705.21],
  ['2022-06-24', 738.2, 708.26, 712.41, 737.12, 31866500, 737.12],
  ['2022-06-27', 756.21, 727.7, 748.1, 734.76, 29726100, 734.76],
  ['2022-06-28', 749.91, 697.03, 733.45, 697.99, 30130400, 697.99],
  ['2022-06-29', 693.52, 666.82, 691.5, 685.47, 27632400, 685.47],
  ['2022-06-30', 688.37, 656.59, 673.53, 673.42, 31533500, 673.42],
  ['2022-07-01', 690.69, 666.36, 681.0, 681.79, 24781500, 681.79],
  ['2022-07-05', 699.44, 648.5, 669.0, 699.2, 28193700, 699.2],
  ['2022-07-06', 703.69, 681.56, 692.34, 695.2, 23951200, 695.2],
  ['2022-07-07', 736.09, 696.63, 701.76, 733.63, 27310200, 733.63],
  ['2022-07-08', 764.94, 723.48, 727.0, 752.29, 33343700, 752.29],
  ['2022-07-11', 759.19, 700.88, 756.31, 703.03, 33080400, 703.03],
  ['2022-07-12', 719.32, 685.11, 710.54, 699.21, 29310300, 699.21],
  ['2022-07-13', 726.18, 675.1, 676.5, 711.12, 32651500, 711.12],
  ['2022-07-14', 715.96, 688.0, 704.69, 714.94, 26069500, 714.94]])

In [14]:
columns, values = get_US_stock()

In [22]:
datas = [value for value in values]
datas

[['2021-12-31', 1082.0, 1054.59, 1073.44, 1056.78, 13577900, 1056.78],
 ['2022-01-03', 1201.07, 1136.04, 1147.75, 1199.78, 34643800, 1199.78],
 ['2022-01-04', 1208.0, 1123.05, 1189.55, 1149.59, 33416100, 1149.59],
 ['2022-01-05', 1170.34, 1081.01, 1146.65, 1088.12, 26706600, 1088.12],
 ['2022-01-06', 1088.0, 1020.5, 1077.0, 1064.7, 30112200, 1064.7],
 ['2022-01-07', 1080.93, 1010.0, 1080.37, 1026.96, 28054900, 1026.96],
 ['2022-01-10', 1059.1, 980.0, 1000.0, 1058.12, 30605000, 1058.12],
 ['2022-01-11', 1075.85, 1038.82, 1053.67, 1064.4, 22021100, 1064.4],
 ['2022-01-12', 1114.84, 1072.59, 1078.85, 1106.22, 27913000, 1106.22],
 ['2022-01-13', 1115.6, 1026.54, 1109.07, 1031.56, 32403300, 1031.56],
 ['2022-01-14', 1052.0, 1013.38, 1019.88, 1049.61, 24308100, 1049.61],
 ['2022-01-18', 1070.79, 1016.06, 1026.61, 1030.51, 22247800, 1030.51],
 ['2022-01-19', 1054.67, 995.0, 1041.71, 995.65, 25147500, 995.65],
 ['2022-01-20', 1041.66, 994.0, 1009.73, 996.27, 23496200, 996.27],
 ['2022-01-21', 1004.55, 940.5, 996.34, 943.9, 34472000, 943.9],
 ['2022-01-24', 933.51, 851.47, 904.76, 930.0, 50521900, 930.0],
 ['2022-01-25', 951.26, 903.21, 914.2, 918.4, 28865300, 918.4],
 ['2022-01-26', 987.69, 906.0, 952.43, 937.41, 34955800, 937.41],
 ['2022-01-27', 935.39, 829.0, 933.36, 829.1, 49036500, 829.1],
 ['2022-01-28', 857.5, 792.01, 831.56, 846.35, 44929700, 846.35],
 ['2022-01-31', 937.99, 862.05, 872.71, 936.72, 34812000, 936.72],
 ['2022-02-01', 943.7, 905.0, 935.21, 931.25, 24379400, 931.25],
 ['2022-02-02', 931.5, 889.41, 928.18, 905.66, 22264300, 905.66],
 ['2022-02-03', 937.0, 880.52, 882.0, 891.14, 26285200, 891.14],
 ['2022-02-04', 936.5, 881.17, 897.22, 923.32, 24541800, 923.32],
 ['2022-02-07', 947.77, 902.71, 923.79, 907.34, 20331500, 907.34],
 ['2022-02-08', 926.29, 894.8, 905.53, 922.0, 16909700, 922.0],
 ['2022-02-09', 946.27, 920.0, 935.0, 932.0, 17419800, 932.0],
 ['2022-02-10', 943.81, 896.7, 908.37, 904.55, 22042300, 904.55],
 ['2022-02-11', 915.96, 850.7, 909.63, 860.0, 26548600, 860.0],
 ['2022-02-14', 898.88, 853.15, 861.57, 875.76, 22585500, 875.76],
 ['2022-02-15', 923.0, 893.38, 900.0, 922.43, 19095400, 922.43],
 ['2022-02-16', 926.43, 901.21, 914.05, 923.39, 17098100, 923.39],
 ['2022-02-17', 918.5, 874.1, 913.26, 876.35, 18392800, 876.35],
 ['2022-02-18', 886.87, 837.61, 886.0, 856.98, 22833900, 856.98],
 ['2022-02-22', 856.73, 801.1, 834.13, 821.53, 27762700, 821.53],
 ['2022-02-23', 835.3, 760.56, 830.43, 764.04, 31752300, 764.04],
 ['2022-02-24', 802.48, 700.0, 700.39, 800.77, 45107400, 800.77],
 ['2022-02-25', 819.5, 782.4, 809.23, 809.87, 25355900, 809.87],
 ['2022-02-28', 876.86, 814.71, 815.01, 870.43, 33002300, 870.43],
 ['2022-03-01', 889.88, 853.78, 869.68, 864.37, 24922300, 864.37],
 ['2022-03-02', 886.48, 844.27, 872.13, 879.89, 24881100, 879.89],
 ['2022-03-03', 886.44, 832.6, 878.77, 839.29, 20541200, 839.29],
 ['2022-03-04', 855.65, 825.16, 849.1, 838.29, 22333200, 838.29],
 ['2022-03-07', 866.14, 804.57, 856.3, 804.58, 24164700, 804.58],
 ['2022-03-08', 849.99, 782.17, 795.53, 824.4, 26799700, 824.4],
 ['2022-03-09', 860.56, 832.01, 839.48, 858.97, 19728000, 858.97],
 ['2022-03-10', 854.45, 810.36, 851.45, 838.3, 19549500, 838.3],
 ['2022-03-11', 843.8, 793.77, 840.2, 795.35, 22345700, 795.35],
 ['2022-03-14', 800.7, 756.04, 780.61, 766.37, 23717400, 766.37],
 ['2022-03-15', 805.57, 756.57, 775.27, 801.89, 22280400, 801.89],
 ['2022-03-16', 842.0, 802.26, 809.0, 840.23, 28009600, 840.23],
 ['2022-03-17', 875.0, 825.72, 830.99, 871.6, 22194300, 871.6],
 ['2022-03-18', 907.85, 867.39, 874.49, 905.39, 33471400, 905.39],
 ['2022-03-21', 942.85, 907.09, 914.98, 921.16, 27327200, 921.16],
 ['2022-03-22', 997.86, 921.75, 930.0, 993.98, 35289500, 993.98],
 ['2022-03-23', 1040.7, 976.4, 979.94, 999.11, 40225400, 999.11],
 ['2022-03-24', 1024.49, 988.8, 1009.73, 1013.92, 22973600, 1013.92],
 ['2022-03-25', 1021.8, 997.32, 1008.0, 1010.64, 20677200, 1010.64],
 ['2022-03-28', 1097.88, 1053.6, 1065.1, 1091.84, 34168700, 1091.84],
 ['2022-03-29', 1114.77, 1073.11, 1107.99, 1099.57, 24538300, 1099.57],
 ['2022-03-30', 1113.95, 1084.0, 1091.17, 1093.99, 19955000, 1093.99],
 ['2022-03-31', 1103.14, 1076.64, 1094.57, 1077.6, 16330900, 1077.6],
 ['2022-04-01', 1094.75, 1066.64, 1081.15, 1084.59, 18087700, 1084.59],
 ['2022-04-04', 1149.91, 1072.53, 1089.38, 1145.45, 27345300, 1145.45],
 ['2022-04-05', 1152.87, 1087.3, 1136.3, 1091.26, 26691700, 1091.26],
 ['2022-04-06', 1079.0, 1027.7, 1073.47, 1045.76, 29782800, 1045.76],
 ['2022-04-07', 1076.59, 1021.54, 1052.39, 1057.26, 26482400, 1057.26],
 ['2022-04-08', 1048.44, 1022.44, 1043.21, 1025.49, 18337900, 1025.49],
 ['2022-04-11', 1008.47, 974.64, 980.4, 975.93, 19785700, 975.93],
 ['2022-04-12', 1021.19, 976.6, 997.64, 986.95, 21992000, 986.95],
 ['2022-04-13', 1026.24, 973.1, 981.08, 1022.37, 18373700, 1022.37],
 ['2022-04-14', 1012.71, 982.19, 999.29, 985.0, 19474100, 985.0],
 ['2022-04-18', 1014.92, 973.41, 989.03, 1004.29, 17238400, 1004.29],
 ['2022-04-19', 1034.94, 995.33, 1005.06, 1028.15, 16615900, 1028.15],
 ['2022-04-20', 1034.0, 975.25, 1030.0, 977.2, 23570400, 977.2],
 ['2022-04-21', 1092.22, 996.42, 1074.73, 1008.78, 35138800, 1008.78],
 ['2022-04-22', 1034.85, 994.0, 1014.91, 1005.05, 23232200, 1005.05],
 ['2022-04-25', 1008.62, 975.3, 978.97, 998.02, 22780400, 998.02],
 ['2022-04-26', 1000.0, 875.0, 995.43, 876.42, 45377900, 876.42],
 ['2022-04-27', 918.0, 877.36, 898.58, 881.51, 25652100, 881.51],
 ['2022-04-28', 900.0, 821.7, 899.98, 877.51, 41649500, 877.51],
 ['2022-04-29', 934.4, 870.0, 902.25, 870.76, 29377700, 870.76],
 ['2022-05-02', 906.36, 848.03, 860.77, 902.94, 25260500, 902.94],
 ['2022-05-03', 924.08, 888.59, 903.18, 909.25, 21236500, 909.25],
 ['2022-05-04', 955.5, 885.28, 903.94, 952.62, 27214600, 952.62],
 ['2022-05-05', 945.6, 857.7, 939.02, 873.28, 30839700, 873.28],
 ['2022-05-06', 888.0, 843.11, 887.0, 865.65, 24301000, 865.65],
 ['2022-05-09', 845.63, 781.15, 836.45, 787.11, 30270100, 787.11],
 ['2022-05-10', 825.36, 774.25, 819.31, 800.04, 28133900, 800.04],
 ['2022-05-11', 809.77, 727.2, 795.0, 734.0, 32408200, 734.0],
 ['2022-05-12', 759.66, 680.0, 701.0, 728.0, 46771000, 728.0],
 ['2022-05-13', 787.35, 751.57, 773.48, 769.59, 30716900, 769.59],
 ['2022-05-16', 769.76, 719.09, 767.16, 724.37, 28699500, 724.37],
 ['2022-05-17', 764.48, 728.85, 747.36, 761.61, 26745400, 761.61],
 ['2022-05-18', 760.5, 700.81, 744.52, 709.81, 29270600, 709.81],
 ['2022-05-19', 734.0, 694.11, 707.0, 709.42, 30098900, 709.42],
 ['2022-05-20', 721.58, 633.0, 713.99, 663.9, 48324400, 663.9],
 ['2022-05-23', 679.96, 638.06, 655.02, 674.9, 29634500, 674.9],
 ['2022-05-24', 653.92, 620.57, 653.53, 628.16, 29697500, 628.16],
 ['2022-05-25', 669.32, 623.01, 623.85, 658.8, 30713100, 658.8],
 ['2022-05-26', 718.67, 653.66, 661.42, 707.73, 35334400, 707.73],
 ['2022-05-27', 759.8, 720.53, 723.25, 759.63, 29765000, 759.63],
 ['2022-05-31', 778.8, 734.23, 773.84, 758.26, 33971500, 758.26],
 ['2022-06-01', 771.98, 730.92, 755.16, 740.37, 25749300, 740.37],
 ['2022-06-02', 792.63, 726.2, 732.47, 775.0, 31157700, 775.0],
 ['2022-06-03', 743.39, 700.25, 729.68, 703.55, 37348100, 703.55],
 ['2022-06-06', 734.6, 703.05, 733.06, 714.84, 28068200, 714.84],
 ['2022-06-07', 719.99, 690.28, 702.0, 716.66, 24269500, 716.66],
 ['2022-06-08', 749.89, 717.53, 720.26, 725.6, 25403500, 725.6],
 ['2022-06-09', 766.64, 717.98, 748.02, 719.12, 32163800, 719.12],
 ['2022-06-10', 718.5, 683.74, 705.47, 696.69, 32512200, 696.69],
 ['2022-06-13', 679.9, 644.05, 669.5, 647.21, 34255800, 647.21],
 ['2022-06-14', 678.99, 635.21, 654.86, 662.67, 32662900, 662.67],
 ['2022-06-15', 706.99, 654.45, 662.75, 699.0, 39710600, 699.0],
 ['2022-06-16', 675.5, 626.08, 668.21, 639.3, 35796900, 639.3],
 ['2022-06-17', 662.91, 639.59, 640.3, 650.28, 30810900, 650.28],
 ['2022-06-21', 730.73, 673.0, 673.81, 711.11, 40931000, 711.11],
 ['2022-06-22', 740.5, 701.48, 703.51, 708.26, 33702500, 708.26],
 ['2022-06-23', 717.95, 685.91, 713.72, 705.21, 34734200, 705.21],
 ['2022-06-24', 738.2, 708.26, 712.41, 737.12, 31866500, 737.12],
 ['2022-06-27', 756.21, 727.7, 748.1, 734.76, 29726100, 734.76],
 ['2022-06-28', 749.91, 697.03, 733.45, 697.99, 30130400, 697.99],
 ['2022-06-29', 693.52, 666.82, 691.5, 685.47, 27632400, 685.47],
 ['2022-06-30', 688.37, 656.59, 673.53, 673.42, 31533500, 673.42],
 ['2022-07-01', 690.69, 666.36, 681.0, 681.79, 24781500, 681.79],
 ['2022-07-05', 699.44, 648.5, 669.0, 699.2, 28193700, 699.2],
 ['2022-07-06', 703.69, 681.56, 692.34, 695.2, 23951200, 695.2],
 ['2022-07-07', 736.09, 696.63, 701.76, 733.63, 27310200, 733.63],
 ['2022-07-08', 764.94, 723.48, 727.0, 752.29, 33343700, 752.29],
 ['2022-07-11', 759.19, 700.88, 756.31, 703.03, 33080400, 703.03],
 ['2022-07-12', 719.32, 685.11, 710.54, 699.21, 29310300, 699.21],
 ['2022-07-13', 726.18, 675.1, 676.5, 711.12, 32651500, 711.12],
 ['2022-07-14', 715.96, 688.0, 704.69, 714.94, 26069500, 714.94]]

In [18]:
datas[0][3] #open
datas[0][4] #close
datas[0][2]  # Low
datas[0][1]  # high

1056.78

In [35]:
day = datas[0][0]

In [37]:
day.replace('-', '/')

'2021/12/31'